version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    command: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0