FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ ./backend
COPY database/ ./database
COPY backend/db.py .
CMD ["sh", "-c", "python backend/db.py && python backend/app.py"]